plugins {
    id('groovy-gradle-plugin')
}

repositories {
    gradlePluginPortal()
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation 'com.github.spotbugs.snom:spotbugs-gradle-plugin:5.2.3'
    implementation 'de.undercouch:gradle-download-task:5.7.0'
    implementation 'gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:1.4.1'
}