plugins {
    id('groovy-gradle-plugin')
}

repositories {
    gradlePluginPortal()
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation 'com.github.spotbugs.snom:spotbugs-gradle-plugin:5.2.3'
    implementation 'ru.vyarus:gradle-animalsniffer-plugin:2.0.1'
    implementation 'de.undercouch:gradle-download-task:5.7.0'
    implementation 'gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:1.4.1'
}