name: "Bug report"
description: "Report an issue with the game"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to submit a thorough issue report for Destination Sol!
        - **Please fill out whichever details below seem relevant to your issue.**
        - **Note that suggestions, general questions & support should go on [Discord](https://discord.gg/Terasology).**
        - **Bug reports and crashes likely resulting from bugs in the engine go here on GitHub.**
  - type: textarea
    id: intent
    attributes:
      label: What you were trying to do
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: What actually happened
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: |
        * Step 1
        * Step 2
        * Step 3
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Game version
      placeholder: '2.0.0'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log details
      description: 'Please attach log files to the text area below'
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
        - Android
        - Other
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 'Additional Info'
    validations:
      required: false
